Update qa-deploy.yml

diff --git a/.github/workflows/qa-deploy.yml b/.github/workflows/qa-deploy.yml
--- a/.github/workflows/qa-deploy.yml
+++ b/.github/workflows/qa-deploy.yml
@@ -8,23 +8,38 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v4
+      - name: Checkout
+        uses: actions/checkout@v4
 
-      - run: sudo apt-get update && sudo apt-get install -y jq
+      - name: Install jq
+        run: sudo apt-get update && sudo apt-get install -y jq
 
       - name: Find ZIP
         run: |
           FILE_PATH=$(find . -name "*.zip" | head -n 1)
           echo "FILE_PATH=$FILE_PATH" >> $GITHUB_ENV
-
-      - name: Deploy iFlow
+      - name: Get Token
+        id: token
+        run: |
+          RESPONSE=$(curl --http1.1 -s -X POST "${{ secrets.CPI_TOKEN_URL }}" \
+            -H "Content-Type: application/x-www-form-urlencoded" \
+            --data-urlencode "grant_type=client_credentials" \
+            --data-urlencode "client_id=${{ secrets.CPI_CLIENT_ID }}" \
+            --data-urlencode "client_secret=${{ secrets.CPI_CLIENT_SECRET }}")
+          echo "$RESPONSE"
+          TOKEN=$(echo "$RESPONSE" | jq -r '.access_token')
+          if [ "$TOKEN" = "null" ] || [ -z "$TOKEN" ]; then
+            echo "OAuth Failed"
+            exit 1
+          fi
+          echo "token=$TOKEN" >> $GITHUB_OUTPUT
+      - name: Deploy
         run: |
           curl --http1.1 -X POST "${{ secrets.CPI_HOST }}/api/v1/IntegrationDesigntimeArtifacts" \
-            -u "${{ secrets.CPI_USERNAME }}:${{ secrets.CPI_PASSWORD }}" \
+            -H "Authorization: Bearer ${{ steps.token.outputs.token }}" \
             -H "Content-Type: application/zip" \
             --data-binary @"$FILE_PATH"
-
-      - name: Activate iFlow
+      - name: Activate
         run: |
           curl --http1.1 -X POST "${{ secrets.CPI_HOST }}/api/v1/IntegrationRuntimeArtifacts/${{ github.event.inputs.artifactId }}/deploy" \
-            -u "${{ secrets.CPI_USERNAME }}:${{ secrets.CPI_PASSWORD }}"
+            -H "Authorization: Bearer ${{ steps.token.outputs.token }}"
